name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Setup Identity
      run: git config --global user.email "daisuke.sysoft@gmail.com" && git config --global user.name "{$GITHUB_ACTOR}"
    - name: Deploy
      run: yarn deploy
